// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductRetrieval.proto

package via.sdj3.animalregistrationapi.protobuf;

public interface AnimalListMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnimalListMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .AnimalMessage animals = 1;</code>
   */
  java.util.List<via.sdj3.animalregistrationapi.protobuf.AnimalMessage> 
      getAnimalsList();
  /**
   * <code>repeated .AnimalMessage animals = 1;</code>
   */
  via.sdj3.animalregistrationapi.protobuf.AnimalMessage getAnimals(int index);
  /**
   * <code>repeated .AnimalMessage animals = 1;</code>
   */
  int getAnimalsCount();
  /**
   * <code>repeated .AnimalMessage animals = 1;</code>
   */
  java.util.List<? extends via.sdj3.animalregistrationapi.protobuf.AnimalMessageOrBuilder> 
      getAnimalsOrBuilderList();
  /**
   * <code>repeated .AnimalMessage animals = 1;</code>
   */
  via.sdj3.animalregistrationapi.protobuf.AnimalMessageOrBuilder getAnimalsOrBuilder(
      int index);
}
