// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductRetrieval.proto

package via.sdj3.animalregistrationapi.protobuf;

public interface IdMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IdMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
