// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductRetrieval.proto

package via.sdj3.animalregistrationapi.protobuf;

public interface NullMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NullMessage)
    com.google.protobuf.MessageOrBuilder {
}
