// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductRetrieval.proto

package via.sdj3.animalregistrationapi.protobuf;

public final class ProductRetrieval {
  private ProductRetrieval() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimalMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimalMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimalListMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimalListMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductMessageCreate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductMessageCreate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IdMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IdMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductListMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductListMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NullMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NullMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ProductRetrieval.proto\"Y\n\rAnimalMessag" +
      "e\022\032\n\022registrationNumber\030\001 \001(\005\022\016\n\006weight\030" +
      "\002 \001(\001\022\014\n\004date\030\003 \001(\t\022\016\n\006origin\030\004 \001(\t\"4\n\021A" +
      "nimalListMessage\022\037\n\007animals\030\001 \003(\0132\016.Anim" +
      "alMessage\"^\n\016ProductMessage\022\n\n\002id\030\001 \001(\005\022" +
      "\r\n\005price\030\002 \001(\001\022\014\n\004name\030\003 \001(\t\022#\n\007animals\030" +
      "\004 \001(\0132\022.AnimalListMessage\"S\n\024ProductMess" +
      "ageCreate\022\n\n\002id\030\001 \001(\005\022\r\n\005price\030\002 \001(\001\022\014\n\004" +
      "name\030\003 \001(\t\022\022\n\nanimalsIds\030\004 \003(\005\"\027\n\tIdMess" +
      "age\022\n\n\002id\030\001 \001(\005\"6\n\022ProductListMessage\022 \n" +
      "\007animals\030\001 \003(\0132\017.ProductMessage\"\r\n\013NullM" +
      "essage2\201\002\n\017ProductsService\0227\n\rcreateProd" +
      "uct\022\025.ProductMessageCreate\032\017.ProductMess" +
      "age\022-\n\016getProductById\022\n.IdMessage\032\017.Prod" +
      "uctMessage\022)\n\rdeleteProduct\022\n.IdMessage\032" +
      "\014.NullMessage\022+\n\006getAll\022\014.NullMessage\032\023." +
      "ProductListMessage\022.\n\013getByAnimal\022\n.IdMe" +
      "ssage\032\023.ProductListMessageB+\n\'via.sdj3.a" +
      "nimalregistrationapi.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AnimalMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AnimalMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimalMessage_descriptor,
        new java.lang.String[] { "RegistrationNumber", "Weight", "Date", "Origin", });
    internal_static_AnimalListMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AnimalListMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimalListMessage_descriptor,
        new java.lang.String[] { "Animals", });
    internal_static_ProductMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProductMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductMessage_descriptor,
        new java.lang.String[] { "Id", "Price", "Name", "Animals", });
    internal_static_ProductMessageCreate_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ProductMessageCreate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductMessageCreate_descriptor,
        new java.lang.String[] { "Id", "Price", "Name", "AnimalsIds", });
    internal_static_IdMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_IdMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IdMessage_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ProductListMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ProductListMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductListMessage_descriptor,
        new java.lang.String[] { "Animals", });
    internal_static_NullMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_NullMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NullMessage_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
