// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductRetrieval.proto

package via.sdj3.animalregistrationapi.protobuf;

public interface ProductMessageCreateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductMessageCreate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>double price = 2;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated int32 animalsIds = 4;</code>
   * @return A list containing the animalsIds.
   */
  java.util.List<java.lang.Integer> getAnimalsIdsList();
  /**
   * <code>repeated int32 animalsIds = 4;</code>
   * @return The count of animalsIds.
   */
  int getAnimalsIdsCount();
  /**
   * <code>repeated int32 animalsIds = 4;</code>
   * @param index The index of the element to return.
   * @return The animalsIds at the given index.
   */
  int getAnimalsIds(int index);
}
