// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductRetrieval.proto

package via.sdj3.animalregistrationapi.protobuf;

public interface ProductListMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductListMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ProductMessage animals = 1;</code>
   */
  java.util.List<via.sdj3.animalregistrationapi.protobuf.ProductMessage> 
      getAnimalsList();
  /**
   * <code>repeated .ProductMessage animals = 1;</code>
   */
  via.sdj3.animalregistrationapi.protobuf.ProductMessage getAnimals(int index);
  /**
   * <code>repeated .ProductMessage animals = 1;</code>
   */
  int getAnimalsCount();
  /**
   * <code>repeated .ProductMessage animals = 1;</code>
   */
  java.util.List<? extends via.sdj3.animalregistrationapi.protobuf.ProductMessageOrBuilder> 
      getAnimalsOrBuilderList();
  /**
   * <code>repeated .ProductMessage animals = 1;</code>
   */
  via.sdj3.animalregistrationapi.protobuf.ProductMessageOrBuilder getAnimalsOrBuilder(
      int index);
}
