// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductRetrieval.proto

package via.sdj3.animalregistrationapi.protobuf;

public interface ProductMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>double price = 2;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.AnimalListMessage animals = 4;</code>
   * @return Whether the animals field is set.
   */
  boolean hasAnimals();
  /**
   * <code>.AnimalListMessage animals = 4;</code>
   * @return The animals.
   */
  via.sdj3.animalregistrationapi.protobuf.AnimalListMessage getAnimals();
  /**
   * <code>.AnimalListMessage animals = 4;</code>
   */
  via.sdj3.animalregistrationapi.protobuf.AnimalListMessageOrBuilder getAnimalsOrBuilder();
}
