// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductRetrieval.proto

package via.sdj3.animalregistrationapi.protobuf;

/**
 * Protobuf type {@code ProductMessageCreate}
 */
public final class ProductMessageCreate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProductMessageCreate)
    ProductMessageCreateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductMessageCreate.newBuilder() to construct.
  private ProductMessageCreate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductMessageCreate() {
    name_ = "";
    animalsIds_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductMessageCreate();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProductMessageCreate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 17: {

            price_ = input.readDouble();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              animalsIds_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            animalsIds_.addInt(input.readInt32());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              animalsIds_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              animalsIds_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        animalsIds_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.animalregistrationapi.protobuf.ProductRetrieval.internal_static_ProductMessageCreate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.animalregistrationapi.protobuf.ProductRetrieval.internal_static_ProductMessageCreate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate.class, via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int PRICE_FIELD_NUMBER = 2;
  private double price_;
  /**
   * <code>double price = 2;</code>
   * @return The price.
   */
  @java.lang.Override
  public double getPrice() {
    return price_;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANIMALSIDS_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.IntList animalsIds_;
  /**
   * <code>repeated int32 animalsIds = 4;</code>
   * @return A list containing the animalsIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getAnimalsIdsList() {
    return animalsIds_;
  }
  /**
   * <code>repeated int32 animalsIds = 4;</code>
   * @return The count of animalsIds.
   */
  public int getAnimalsIdsCount() {
    return animalsIds_.size();
  }
  /**
   * <code>repeated int32 animalsIds = 4;</code>
   * @param index The index of the element to return.
   * @return The animalsIds at the given index.
   */
  public int getAnimalsIds(int index) {
    return animalsIds_.getInt(index);
  }
  private int animalsIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      output.writeDouble(2, price_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (getAnimalsIdsList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(animalsIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < animalsIds_.size(); i++) {
      output.writeInt32NoTag(animalsIds_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, price_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < animalsIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(animalsIds_.getInt(i));
      }
      size += dataSize;
      if (!getAnimalsIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      animalsIdsMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate)) {
      return super.equals(obj);
    }
    via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate other = (via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate) obj;

    if (getId()
        != other.getId()) return false;
    if (java.lang.Double.doubleToLongBits(getPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPrice())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getAnimalsIdsList()
        .equals(other.getAnimalsIdsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getAnimalsIdsCount() > 0) {
      hash = (37 * hash) + ANIMALSIDS_FIELD_NUMBER;
      hash = (53 * hash) + getAnimalsIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProductMessageCreate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProductMessageCreate)
      via.sdj3.animalregistrationapi.protobuf.ProductMessageCreateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.animalregistrationapi.protobuf.ProductRetrieval.internal_static_ProductMessageCreate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.animalregistrationapi.protobuf.ProductRetrieval.internal_static_ProductMessageCreate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate.class, via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate.Builder.class);
    }

    // Construct using via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      price_ = 0D;

      name_ = "";

      animalsIds_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.animalregistrationapi.protobuf.ProductRetrieval.internal_static_ProductMessageCreate_descriptor;
    }

    @java.lang.Override
    public via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate getDefaultInstanceForType() {
      return via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate build() {
      via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate buildPartial() {
      via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate result = new via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.price_ = price_;
      result.name_ = name_;
      if (((bitField0_ & 0x00000001) != 0)) {
        animalsIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.animalsIds_ = animalsIds_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate) {
        return mergeFrom((via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate other) {
      if (other == via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.animalsIds_.isEmpty()) {
        if (animalsIds_.isEmpty()) {
          animalsIds_ = other.animalsIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAnimalsIdsIsMutable();
          animalsIds_.addAll(other.animalsIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <code>double price = 2;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }
    /**
     * <code>double price = 2;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double price = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList animalsIds_ = emptyIntList();
    private void ensureAnimalsIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        animalsIds_ = mutableCopy(animalsIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 animalsIds = 4;</code>
     * @return A list containing the animalsIds.
     */
    public java.util.List<java.lang.Integer>
        getAnimalsIdsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(animalsIds_) : animalsIds_;
    }
    /**
     * <code>repeated int32 animalsIds = 4;</code>
     * @return The count of animalsIds.
     */
    public int getAnimalsIdsCount() {
      return animalsIds_.size();
    }
    /**
     * <code>repeated int32 animalsIds = 4;</code>
     * @param index The index of the element to return.
     * @return The animalsIds at the given index.
     */
    public int getAnimalsIds(int index) {
      return animalsIds_.getInt(index);
    }
    /**
     * <code>repeated int32 animalsIds = 4;</code>
     * @param index The index to set the value at.
     * @param value The animalsIds to set.
     * @return This builder for chaining.
     */
    public Builder setAnimalsIds(
        int index, int value) {
      ensureAnimalsIdsIsMutable();
      animalsIds_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 animalsIds = 4;</code>
     * @param value The animalsIds to add.
     * @return This builder for chaining.
     */
    public Builder addAnimalsIds(int value) {
      ensureAnimalsIdsIsMutable();
      animalsIds_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 animalsIds = 4;</code>
     * @param values The animalsIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllAnimalsIds(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureAnimalsIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, animalsIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 animalsIds = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnimalsIds() {
      animalsIds_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ProductMessageCreate)
  }

  // @@protoc_insertion_point(class_scope:ProductMessageCreate)
  private static final via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate();
  }

  public static via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductMessageCreate>
      PARSER = new com.google.protobuf.AbstractParser<ProductMessageCreate>() {
    @java.lang.Override
    public ProductMessageCreate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductMessageCreate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductMessageCreate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductMessageCreate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.animalregistrationapi.protobuf.ProductMessageCreate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

