// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalRetrieval.proto

package via.sdj3.animalregistrationapi.protobuf;

/**
 * Protobuf type {@code RegistrationNumbersMessage}
 */
public final class RegistrationNumbersMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RegistrationNumbersMessage)
    RegistrationNumbersMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RegistrationNumbersMessage.newBuilder() to construct.
  private RegistrationNumbersMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegistrationNumbersMessage() {
    registrationNumbers_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RegistrationNumbersMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RegistrationNumbersMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              registrationNumbers_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            registrationNumbers_.addInt(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              registrationNumbers_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              registrationNumbers_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        registrationNumbers_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.animalregistrationapi.protobuf.AnimalRetrieval.internal_static_RegistrationNumbersMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.animalregistrationapi.protobuf.AnimalRetrieval.internal_static_RegistrationNumbersMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage.class, via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage.Builder.class);
  }

  public static final int REGISTRATIONNUMBERS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.IntList registrationNumbers_;
  /**
   * <code>repeated int32 registrationNumbers = 1;</code>
   * @return A list containing the registrationNumbers.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getRegistrationNumbersList() {
    return registrationNumbers_;
  }
  /**
   * <code>repeated int32 registrationNumbers = 1;</code>
   * @return The count of registrationNumbers.
   */
  public int getRegistrationNumbersCount() {
    return registrationNumbers_.size();
  }
  /**
   * <code>repeated int32 registrationNumbers = 1;</code>
   * @param index The index of the element to return.
   * @return The registrationNumbers at the given index.
   */
  public int getRegistrationNumbers(int index) {
    return registrationNumbers_.getInt(index);
  }
  private int registrationNumbersMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getRegistrationNumbersList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(registrationNumbersMemoizedSerializedSize);
    }
    for (int i = 0; i < registrationNumbers_.size(); i++) {
      output.writeInt32NoTag(registrationNumbers_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < registrationNumbers_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(registrationNumbers_.getInt(i));
      }
      size += dataSize;
      if (!getRegistrationNumbersList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      registrationNumbersMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage)) {
      return super.equals(obj);
    }
    via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage other = (via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage) obj;

    if (!getRegistrationNumbersList()
        .equals(other.getRegistrationNumbersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRegistrationNumbersCount() > 0) {
      hash = (37 * hash) + REGISTRATIONNUMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getRegistrationNumbersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RegistrationNumbersMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RegistrationNumbersMessage)
      via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.animalregistrationapi.protobuf.AnimalRetrieval.internal_static_RegistrationNumbersMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.animalregistrationapi.protobuf.AnimalRetrieval.internal_static_RegistrationNumbersMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage.class, via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage.Builder.class);
    }

    // Construct using via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      registrationNumbers_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.animalregistrationapi.protobuf.AnimalRetrieval.internal_static_RegistrationNumbersMessage_descriptor;
    }

    @java.lang.Override
    public via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage getDefaultInstanceForType() {
      return via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage build() {
      via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage buildPartial() {
      via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage result = new via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        registrationNumbers_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.registrationNumbers_ = registrationNumbers_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage) {
        return mergeFrom((via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage other) {
      if (other == via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage.getDefaultInstance()) return this;
      if (!other.registrationNumbers_.isEmpty()) {
        if (registrationNumbers_.isEmpty()) {
          registrationNumbers_ = other.registrationNumbers_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRegistrationNumbersIsMutable();
          registrationNumbers_.addAll(other.registrationNumbers_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList registrationNumbers_ = emptyIntList();
    private void ensureRegistrationNumbersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        registrationNumbers_ = mutableCopy(registrationNumbers_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 registrationNumbers = 1;</code>
     * @return A list containing the registrationNumbers.
     */
    public java.util.List<java.lang.Integer>
        getRegistrationNumbersList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(registrationNumbers_) : registrationNumbers_;
    }
    /**
     * <code>repeated int32 registrationNumbers = 1;</code>
     * @return The count of registrationNumbers.
     */
    public int getRegistrationNumbersCount() {
      return registrationNumbers_.size();
    }
    /**
     * <code>repeated int32 registrationNumbers = 1;</code>
     * @param index The index of the element to return.
     * @return The registrationNumbers at the given index.
     */
    public int getRegistrationNumbers(int index) {
      return registrationNumbers_.getInt(index);
    }
    /**
     * <code>repeated int32 registrationNumbers = 1;</code>
     * @param index The index to set the value at.
     * @param value The registrationNumbers to set.
     * @return This builder for chaining.
     */
    public Builder setRegistrationNumbers(
        int index, int value) {
      ensureRegistrationNumbersIsMutable();
      registrationNumbers_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 registrationNumbers = 1;</code>
     * @param value The registrationNumbers to add.
     * @return This builder for chaining.
     */
    public Builder addRegistrationNumbers(int value) {
      ensureRegistrationNumbersIsMutable();
      registrationNumbers_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 registrationNumbers = 1;</code>
     * @param values The registrationNumbers to add.
     * @return This builder for chaining.
     */
    public Builder addAllRegistrationNumbers(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureRegistrationNumbersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, registrationNumbers_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 registrationNumbers = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegistrationNumbers() {
      registrationNumbers_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RegistrationNumbersMessage)
  }

  // @@protoc_insertion_point(class_scope:RegistrationNumbersMessage)
  private static final via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage();
  }

  public static via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegistrationNumbersMessage>
      PARSER = new com.google.protobuf.AbstractParser<RegistrationNumbersMessage>() {
    @java.lang.Override
    public RegistrationNumbersMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RegistrationNumbersMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RegistrationNumbersMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegistrationNumbersMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.animalregistrationapi.protobuf.RegistrationNumbersMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

