// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalRetrieval.proto

package via.sdj3.animalregistrationapi.protobuf;

public interface RegistrationNumbersMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegistrationNumbersMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 registrationNumbers = 1;</code>
   * @return A list containing the registrationNumbers.
   */
  java.util.List<java.lang.Integer> getRegistrationNumbersList();
  /**
   * <code>repeated int32 registrationNumbers = 1;</code>
   * @return The count of registrationNumbers.
   */
  int getRegistrationNumbersCount();
  /**
   * <code>repeated int32 registrationNumbers = 1;</code>
   * @param index The index of the element to return.
   * @return The registrationNumbers at the given index.
   */
  int getRegistrationNumbers(int index);
}
