// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalRetrieval.proto

package via.sdj3.animalregistrationapi.protobuf;

public interface StringParameterMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StringParameterMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
